source 'https://rubygems.org'

gem 'capybara', '3.35.3'
gem 'cucumber', '3.1.2'
gem 'faker'
gem 'ffaker'
gem 'pry', '0.11.3'
gem 'rspec'
gem 'rubytree', '1.0.0'
gem 'screen-recorder'
gem 'selenium-webdriver', '3.142.7'
gem 'ffmpeg'
